### PR TITLE
index start/count for drawcalls

### LINKED ISSUE #408: Mesh.MergeMeshes does not work correctly with multiple materials
If you create two meshes (e.g. `Mesh.CreateBox`) and they each have a different material, and then you merge them with `Mesh.MergeMeshes([box1, box2], true, true, undefined, undefined, true)` the geometry merges as expected, but you end up with a single material which looks kind of like one of the original materials but without the alpha (or something like that). Same thing works fine in the Babylon.js Playground.

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes #408

### CODE REVIEW

**Review by ryantrem — APPROVED** [review]

File: Plugins/NativeEngine/Source/NativeEngine.cpp [hunk 1]
```diff
@@ -768,10 +768,7 @@ namespace Babylon
         const auto& vertexArray = *(info[0].As<Napi::External<VertexArray>>().Data());
 
         // a vertex array might not have an index buffer associated with
```
Comment (bghgary) [inline Plugins/NativeEngine/Source/NativeEngine.cpp:770]: this comment doesn't make sense now

File: Plugins/NativeEngine/Source/NativeEngine.cpp [hunk 2]
```diff
@@ -768,10 +768,7 @@ namespace Babylon
...
-        if (vertexArray.indexBuffer.data)
-        {
-            vertexArray.indexBuffer.data->SetBgfxIndexBuffer();
-        }
+        m_currentBoundIndexBuffer = vertexArray.indexBuffer.data;
```
Comment (bghgary) [inline Plugins/NativeEngine/Source/NativeEngine.cpp:771]: Given the way things are going, I wonder if it would be cleaner to store the vertexArray instead of just the index buffer. Then do the bgfx work when draw is called.

**Review by bghgary — CHANGES_REQUESTED** [review]

File: Plugins/NativeEngine/Source/NativeEngine.cpp (hunk 1 above)
Comment (CedricGuillemet) [reply Plugins/NativeEngine/Source/NativeEngine.cpp:770]: It does! the m_currentBoundIndexBuffer is updated with the index buffer associated with it. It can be nullptr.

Comment (bghgary) [reply Plugins/NativeEngine/Source/NativeEngine.cpp:770]: Oh, right, sorry, I misinterpreted the comment.

File: Plugins/NativeEngine/Source/NativeEngine.cpp (hunk 2 above)
Comment (CedricGuillemet) [reply Plugins/NativeEngine/Source/NativeEngine.cpp:771]: Not sure if a vertex/indexbuffer is bound once with multiple drawcalls depending on it. But maybe in the future. I see a trend to store a lot more states in nativeengine class (clear/rendering states/index buffer).

Comment (bghgary) [reply Plugins/NativeEngine/Source/NativeEngine.cpp:771]: We should probably take care of this sooner than later.

**Review by bghgary — APPROVED** [review]
