### PR TITLE
 Fixes for Android shader compile

### LINKED ISSUE #371: Normals map not rendering correctly with BabylonReactNative demo app
Rendering like this in the demo app:

Same asset loaded in Sandbox:

To repro, use this asset:
https://raw.githubusercontent.com/RonnieAshlock/TestAssets/master/GLB/Head/Head_512Tex.glb

### PR DESCRIPTION
**Pull request by bghgary**
Fixes #371, #372, #385.

Also fixes BabylonJS/BabylonReactNative#61 once BabylonReactNative picks up this change.

The main issue with the Android shader code path is that the sampler locations for textures are wrong. This change include a couple of fixes to address this:

1. The conversion to SPIRV is now as minimal as possible. The splitting of samplers into texture/sampler and then recombining them is now gone. [Removing SPIRV for OpenGL situations](https://github.com/BabylonJS/BabylonNative/issues/300) should be easier after this change. This is a problem because when SPIRV recombines the texture/sampler pair, it mangles the name and thus bgfx can't bind the locations properly. I couldn't find a way for SPIRV not to do this, but removing this splitting/recombining fixes this issue. Lowering to ES 300 version also then removes the binding attributes completely.
2. Because the binding has been removed completely, the "stage" as bgfx calls them, needs to be generated explicitly. As far as I can tell, for WebGL/OpenGL, this is simply the order they appear in the shader. The change to AppendSamplers reflects this fix.

Finally, I purposefully did not fix Linux in this change. I expect Linux will have exactly the same issue as Android, but I don't want to handle that in this PR. Will address it separately.

### CODE REVIEW

File: Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp [hunk 1]
```diff
@@ -36,12 +36,14 @@ namespace Babylon
...
+#if !ANDROID
             compiler->build_combined_image_samplers();
+#endif
 
             spirv_cross::CompilerGLSL::Options options = compiler->get_common_options();
 
-#ifdef ANDROID
-            options.version = 310;
+#if ANDROID
+            options.version = 300;
```
Comment (syntheticmagus) [inline Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp:46]: Does this work? I seem to remember there was some issue with 300, like SPIRV-Cross had some sort of problem with that version.

Comment (bghgary) [reply Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp:46]: What do you mean by "in isolation"? It certainly works for ANDROID builds AFAICT.

Comment (bghgary) [reply Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp:46]: BTW, this change is what removes the binding attributes. Bindings are not supported until 310, but using 310 causes the bindings to output with locations of 0 for each one. WebGL2 conforms closely to OpenGL ES 3.0. We should use 3.0 unless there is a specific reason not to.

Comment (syntheticmagus) [reply Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp:46]: By "in isolation," I meant were there other changes (for example, a different SPIRV-Cross submodule version) that weren't reflected here that caused this to work (realizing it's a draft and might not be complete). I don't remember exactly what it was, but _something_ led us to decide to use GLSL 310 instead of 300. If that was the bindings thing and it no longer applies, that's awesome!

Comment (bghgary) [reply Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp:46]: I don't remember/know for sure. But this change is tied with the removal of the the split and recombine in this file.

**Review by syntheticmagus — APPROVED** [review]
