### PR TITLE
XRRay object Check

### LINKED ISSUE #997: iOS ARKit XRHitTest "Invalid Argument" Error In Playground Demo
**Describe the bug**
On the latest master commit, I'm having issues across multiple devices (iPhone 13 Pro / iPhone 11 / iPad Pro) enabling both AR and XRHitTest in experience.js with the playground demo.

**To Reproduce**
1. My configuration variables in experience.js look like the following:

```
var wireframe = false;
var turntable = false;
var logfps = false;
var ibl = false;
var rtt = false;
var vr = false;
var ar = true;
var xrHitTest = true;
var xrFeaturePoints = false;
var meshDetection = false;
var text = false;
var hololens = false;
var cameraTexture = false;
```

**Expected behavior**
Expect to see the cube in AR and be able to place it.

**Actual behavior**
AR scene never loads, get the following error in the log:

```
2022-02-10 12:32:32.206247-0500 Playground[382:7972] Error: Invalid argument
2022-02-10 12:32:32.206310-0500 Playground[382:7972] Invalid argument
```

Also want to note that the ARKit scene does load if only "ar" is true and "xrHitTest" is false.

**Other**
 - Tested on various iOS versions from iOS 13 - iOS 15

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes #997 

It was broken for every platforms. It didn't check the napi object could be unwrapped (exception) .

### CODE REVIEW

File: Plugins/NativeXr/Source/NativeXr.cpp [hunk 1]
```diff
@@ -1338,9 +1339,11 @@ namespace Babylon
                 {
                     auto argumentObject{info[0].As<Napi::Object>()};
 
-                    XRRigidTransform* transform{XRRigidTransform::Unwrap(argumentObject)};
-                    if (transform != nullptr)
+                    const auto XRRigidTransformFunction = Env().Global().Get(XRRigidTransform::JS_CLASS_NAME).As<Napi::Function>();
+
+                    if (argumentObject.InstanceOf(XRRigidTransformFunction))
```
Comment (ryantrem) [inline Plugins/NativeXr/Source/NativeXr.cpp:1344]: Under what circumstances will this not be true?

Comment (bghgary) [reply Plugins/NativeXr/Source/NativeXr.cpp:1344]: InstanceOf is a very slow check. Is there some property you can check instead?

**Review by bghgary — APPROVED** [review]

File: Plugins/NativeXr/Source/NativeXr.cpp (hunk 1 above)
Comment (CedricGuillemet) [reply Plugins/NativeXr/Source/NativeXr.cpp]: Using property check instead.
