### PR TITLE
GCC10 + Latest SPIRV-cross

### LINKED ISSUE #679: Build Fail on Fedora Linux SPIRV-Cross comparison of unsigned expression in '< 0' is always false
Hey,

testing build on fedora, i get this build error 

```
FAILED: Dependencies/SPIRV-Cross/CMakeFiles/spirv-cross-core.dir/spirv_cfg.cpp.o 
/usr/bin/c++  -I../Dependencies/SPIRV-Cross -Wall -Wextra -Werror -Wshadow -Wno-cpp -std=gnu++11 -MD -MT Dependencies/SPIRV-Cross/CMakeFiles/spirv-cross-core.dir/spirv_cfg.cpp.o -MF Dependencies/SPIRV-Cross/CMakeFiles/spirv-cross-core.dir/spirv_cfg.cpp.o.d -o Dependencies/SPIRV-Cross/CMakeFiles/spirv-cross-core.dir/spirv_cfg.cpp.o -c ../Dependencies/SPIRV-Cross/spirv_cfg.cpp
In file included from ../Dependencies/SPIRV-Cross/spirv_common.hpp:21,
                 from ../Dependencies/SPIRV-Cross/spirv_cfg.hpp:20,
                 from ../Dependencies/SPIRV-Cross/spirv_cfg.cpp:17:
../Dependencies/SPIRV-Cross/spirv_cross_containers.hpp: In instantiation of 'void spirv_cross::SmallVector<T, N>::reserve(size_t) [with T = spirv_cross::SPIRUndef*; long unsigned int N = 0; size_t = long unsigned int]':
../Dependencies/SPIRV-Cross/spirv_cross_containers.hpp:293:3:   required from 'void spirv_cross::SmallVector<T, N>::push_back(T&&) [with T = spirv_cross::SPIRUndef*; long unsigned int N = 0]'
../Dependencies/SPIRV-Cross/spirv_cross_containers.hpp:540:22:   required from 'T* spirv_cross::ObjectPool<T>::allocate(P&& ...) [with P = {spirv_cross::SPIRUndef&}; T = spirv_cross::SPIRUndef]'
../Dependencies/SPIRV-Cross/spirv_common.hpp:319:2:   required from here
../Dependencies/SPIRV-Cross/spirv_cross_containers.hpp:321:24: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
  321 |    if (target_capacity < N)
      |        ~~~~~~~~~~~~~~~~^~~
```
https://gist.github.com/arpu/77665918c690932e858eeccfaf7daa40

### PR DESCRIPTION
**Pull request by CedricGuillemet**
- enable decoration bindings for Metal texture association
- update SPIRV
- update iOS validation tests
- enable GCC10 build on AzurePipelines fixes #679

### CODE REVIEW

File: Plugins/NativeEngine/Source/ShaderCompilerCommon.cpp [hunk 1]
```diff
@@ -172,7 +172,7 @@ namespace Babylon::ShaderCompilerCommon
             const auto& compiler = *vertexShaderInfo.Compiler;
             const spirv_cross::ShaderResources resources = compiler.get_shader_resources();
             auto uniformsInfo = CollectNonSamplerUniforms(*vertexShaderInfo.Parser, compiler);
-#if (BGFX_CONFIG_RENDERER_METAL)
+#if __APPLE__
```
Comment (bghgary) [inline Plugins/NativeEngine/Source/ShaderCompilerCommon.cpp:175]: why is this better than the previous define?

**Review by bghgary — APPROVED** [review]

File: Plugins/NativeEngine/Source/ShaderCompilerCommon.cpp (hunk 1 above)
Comment (CedricGuillemet) [reply Plugins/NativeEngine/Source/ShaderCompilerCommon.cpp:175]: Not better, but more consistent with checks in other cpp like ShaderCompilerTraversers.

Comment (bghgary) [reply Plugins/NativeEngine/Source/ShaderCompilerCommon.cpp:175]: Apple in theory can use OpenGL even though it's deprecated, so maybe the other define is better than checking __APPLE__
