### PR TITLE
Fix Mixed Reality Capture for HoloLens

### LINKED ISSUE #830: Taking a Mixed Reality Capture crashes the app
It seems that even opening the MRC preview in the device portal for HoloLens 2 will crash the app. 

It was due to some incorrect logic in the secondary view configuration setup that wasn't initializing swapchains because the recommended view dimensions were the same, disregarding the fact that the swapchains hadn't been initialized.

This comment was to remind us that we still needed to initialize the secondary view config swapchains when they're needed:
https://github.com/BabylonJS/BabylonNative/blob/00ea35e7dfc7622d25f1bf45d502f4061ad96c63/Dependencies/xr/Source/OpenXR/XR.cpp#L661-L662

But when we get to this bit, we don't see any resizing because the secondary view configurations were already initialized with the correct recommended dimensions, we just don't check if the swapchains have been initialized yet:
https://github.com/BabylonJS/BabylonNative/blob/00ea35e7dfc7622d25f1bf45d502f4061ad96c63/Dependencies/xr/Source/OpenXR/XR.cpp#L1477-L1481

### PR DESCRIPTION
**Pull request by rgerd**
fixes #830 and cleans up some of the logic around secondary view configurations.

### CODE REVIEW

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 1]
```diff
@@ -985,19 +985,20 @@ namespace xr
...
+                };
                 secondaryViewConfigCreateInfo.viewConfigurationType = viewConfigType;
                 swapchainCreateInfo.next = &secondaryViewConfigCreateInfo;
             }
 
             XrCheck(xrCreateSwapchain(session, &swapchainCreateInfo, &swapchain.Handle));
 
-            uint32_t chainLength;
+            uint32_t chainLength = 0;
             XrCheck(xrEnumerateSwapchainImages(swapchain.Handle, 0, &chainLength, nullptr));
```
Comment (chrisfromwork) [inline Dependencies/xr/Source/OpenXR/XR.cpp:1002]: nit: uint32_t chainLength{0};

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 2]
```diff
@@ -1460,31 +1455,31 @@ namespace xr
...
-                if (viewState.Active)
-                {
-                    std::vector<XrViewConfigurationView> viewConfigViews = EnumerateViewConfigurationViews(
-                        sessionImpl.HmdImpl.Context.Instance(),
-                        sessionImpl.HmdImpl.Context.SystemId(),
-                        secondaryViewConfigState.viewConfigurationType);
+                std::vector<XrViewConfigurationView> viewConfigViews = EnumerateViewConfigurationViews(
+                    sessionImpl.HmdImpl.Context.Instance(),
+                    sessionImpl.HmdImpl.Context.SystemId(),
+                    secondaryViewConfigState.viewConfigurationType);
```
Comment (chrisfromwork) [inline Dependencies/xr/Source/OpenXR/XR.cpp:1470]: nit: remove spaces

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 3]
```diff
@@ -1460,31 +1455,31 @@ namespace xr
...
-                }
-                else
+                if (IsRecommendedSwapchainSizeChanged(viewState.ViewConfigViews, viewConfigViews) ||
+                    colorSwapchainHandle == XR_NULL_HANDLE)
                 {
-                    sessionImpl.CleanupSwapchains(viewState);
+                    viewState.ViewConfigViews = std::move(viewConfigViews);
+                    sessionImpl.PopulateSwapchains(viewState);
+                    (void)viewConfigViews;
                 }
```
Comment (chrisfromwork) [inline Dependencies/xr/Source/OpenXR/XR.cpp:1477]: what is this for?

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 4]
```diff
@@ -1852,12 +1842,12 @@ namespace xr
             frameEndInfo.layers = &layersPtr;
```
Comment (chrisfromwork) [inline Dependencies/xr/Source/OpenXR/XR.cpp:1843]: nit: remove extra spaces

**Comment by chrisfromwork** [comment]
>                     XrCompositionLayerBaseHeader* secondaryLayersPtr = reinterpret_cast<XrCompositionLayerBaseHeader*>(&secondaryViewLayer);

is this memory valid outside the for loop? This looks like we set a pointer to memory thats invalidated once the loop is completed?

---
Refers to: Dependencies/xr/Source/OpenXR/XR.cpp:1857 in b14963b. [](commit_id = b14963bd7590ad41f8b32afa1b57ac46e11b1bd2, deletion_comment = False)

**Comment by chrisfromwork** [comment]
>                     XrCompositionLayerBaseHeader* secondaryLayersPtr = reinterpret_cast<XrCompositionLayerBaseHeader*>(&secondaryViewLayer);

the previous layers vector was clunky, but it was insuring that the structs still existed on the stack

---
In reply to: [881582063](https://github.com/BabylonJS/BabylonNative/pull/831#issuecomment-881582063) [](http://example.com/codeflow?ancestors=881582063)

---
Refers to: Dependencies/xr/Source/OpenXR/XR.cpp:1857 in b14963b. [](commit_id = b14963bd7590ad41f8b32afa1b57ac46e11b1bd2, deletion_comment = False)

File: Dependencies/xr/Source/OpenXR/XR.cpp (hunk 3 above)
Comment (chrisfromwork) [reply Dependencies/xr/Source/OpenXR/XR.cpp:1477]: the (void)viewConfigViews line

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 5]
```diff
@@ -985,19 +985,20 @@ namespace xr
...
 
-            XrSecondaryViewConfigurationSwapchainCreateInfoMSFT secondaryViewConfigCreateInfo
-            {
-                XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT
-            };
-            if (HmdImpl.Context.Extensions()->SecondaryViewConfigurationSupported)
+            if (HmdImpl.Context.Extensions()->SecondaryViewConfigurationSupported && 
+                viewConfigType == XR_VIEW_CONFIGURATION_TYPE_SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT)
             {
+                XrSecondaryViewConfigurationSwapchainCreateInfoMSFT secondaryViewConfigCreateInfo
```
Comment (yl-msft) [inline Dependencies/xr/Source/OpenXR/XR.cpp:991]: This variable need to be moved out of the if block, to keep it at same lifetime as the xrCreateSwapchain function below.  Otherwise, the memory in the stack might be overwritten when the function is called below.

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 6]
```diff
@@ -1059,17 +1060,17 @@ namespace xr
...
-
+                const auto& supportedSecondaryViewConfigTypes = HmdImpl.SupportedSecondaryViewConfigurationTypes;
                 if (HmdImpl.Context.Extensions()->SecondaryViewConfigurationSupported &&
                     HmdImpl.Context.Extensions()->FirstPersonObserverSupported &&
-                    HmdImpl.SupportedSecondaryViewConfigurationTypes.size() > 0)
+                    supportedSecondaryViewConfigTypes.size() > 0)
                 {
-                    secondaryViewConfigInfo.viewConfigurationCount = static_cast<uint32_t>(HmdImpl.SupportedSecondaryViewConfigurationTypes.size());
-                    secondaryViewConfigInfo.enabledViewConfigurationTypes = HmdImpl.SupportedSecondaryViewConfigurationTypes.data();
+                    XrSecondaryViewConfigurationSessionBeginInfoMSFT secondaryViewConfigInfo
```
Comment (yl-msft) [inline Dependencies/xr/Source/OpenXR/XR.cpp:1068]: Similarly, this variable definition need to be moved outside of the if block.

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 7]
```diff
@@ -1436,18 +1437,12 @@ namespace xr
...
         {
-            uint32_t viewCount = 0;
-            for (const auto& viewConfigurationType : sessionImpl.HmdImpl.SupportedSecondaryViewConfigurationTypes)
-            {
-                const auto& viewState = renderResources.ResourceMap.at(viewConfigurationType).ViewState;
-                viewCount += static_cast<uint32_t>(viewState.Views.size());
-            }
-
-            secondaryViewConfigStates.resize(viewCount, { XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT });
+            XrSecondaryViewConfigurationFrameStateMSFT secondaryViewConfigFrameState{XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT};
```
Comment (yl-msft) [inline Dependencies/xr/Source/OpenXR/XR.cpp:1445]: Here as well.  The variable definition need to be moved out of the if block and keep it alive when calling the xr function below.

File: Dependencies/xr/Source/OpenXR/XR.cpp [hunk 8]
```diff
@@ -1850,21 +1839,23 @@ namespace xr
...
-                    XrSecondaryViewConfigurationLayerInfoMSFT& secondaryViewLayerInfo = activeSecondaryViewConfigLayerInfos.at(i);
-                    layers[i + 1] = { XR_TYPE_COMPOSITION_LAYER_PROJECTION };
-                    XrCompositionLayerProjection& secondaryViewLayer = layers.at(i + 1);
                     secondaryViewLayer.layerFlags = XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT;
                     secondaryViewLayer.space = sceneSpace;
-                    const auto& secondaryRenderResource = renderResources.ResourceMap.at(secondaryViewLayerInfo.viewConfigurationType);
                     secondaryViewLayer.viewCount = static_cast<uint32_t>(secondaryRenderResource.ProjectionLayerViews.size());
                     secondaryViewLayer.views = secondaryRenderResource.ProjectionLayerViews.data();
+
                     secondaryViewLayerInfo.layerCount = 1;
```
Comment (chrisfromwork) [inline Dependencies/xr/Source/OpenXR/XR.cpp:1858]: nit: remove added line

**Review by chrisfromwork — APPROVED** [review]
